kind: pipeline
name: Drone

workspace:
  path: /drone/src

steps:
 - name: compile
   image: geopd/builder:drone
   environment:
     bottoken:
       from_secret: bottoken
     chatid:
       from_secret: chatid
     repo1:
       from_secret: repo1
     repo2:
       from_secret: repo2
   commands:
      - bash kernel_compile.sh
trigger:
  branch:
  - master
  event:
  - push